### PR TITLE
Adds option to display orb instead of metric

### PR DESCRIPTION
**Pull request by leonhardhaas**
Hello.
First of all great job on creating the panel.

I missed the functionality to only display a colored orb (like a traffic light) in the image without text.
This functionality is now added to the panel.

The screenshot shows, the added input elements:

- a checkbox which specifies, if an orb should be displayed instead of the *PREFIX + METRIC + SUFFIX* part
- a input-field which can be used to set the size of the orb

panel

I am looking forward to hear of you.

With best regards,
Leo

### CODE REVIEW

**Comment by leonhardhaas** [comment]
Hello again.

I now added the option to display the orb and metric simultaneously.
When doing so you can select on which side the orb should appear.

panel-appearance

With best regards.
Leo

**Comment by LucasArona** [comment]
Hello,

thank you very much for your contribution ! Orbs are great 👍

Can you just check the CSS class here:

https://github.com/LucasArona/larona-epict-panel/blob/3038f439f0c3f0c40f2bccbf0362779d5df881fa/src/editor.html#L94

I think it should be `gf-form-inline` instead of `gf-form` to remove the gap between "Hide text" and "Use thresholds"

And here:
https://github.com/LucasArona/larona-epict-panel/blob/3038f439f0c3f0c40f2bccbf0362779d5df881fa/src/editor.html#L100

I think we should use width-8 instead of 6, otherwise the text is truncated once the user selected it (Right is shown as "Righ" and "Bottom" as "Bott")
This implies also updating the input size for `orb-size` and `font-size` to keep things aligned.

Thanks again !
Best,
Lucas

**Comment by leonhardhaas** [comment]
Hello again.

Fixed width of input fields to have uniform length of 8.
Changed css-class from `gf-form` to `gf-form-inline`.

A short question from my side:
Do you know what could cause the offset displayed in the image?

offset

With best regards.
Leo

**Comment by LucasArona** [comment]
I did some tests with the offset you are talking about: I concluded that the checkboxes and inputs do not align. We can see the same offset even in the built-in "Heatmap" plugin (screenshot from Grafana v6 but we can see the offset too) : 
image

Thanks for the modifications, however I just saw that you wrote "dif" instead of "div" in this area:

https://github.com/LucasArona/larona-epict-panel/blob/331e6e7f760ff001229d3bd72c830dc0b56e50b4/dist/editor.html#L97

**Comment by leonhardhaas** [comment]
I replaced all `dif` occurences by `div` in editor.html.
Sorry for the mixup.

Do you have any more important points that need to be changed?

**Comment by LucasArona** [comment]
Looks good to me 👍
thanks

**Comment by leonhardhaas** [comment]
Hello again.

Just a short question from my side:
How long do you think does it take, until 1.2 of the panel is available for install using grafana-cli?

With best regards.
Leo

**Comment by LucasArona** [comment]
Hello !
this is the process:
I submitted the request to Grafana, they will review the code and approve the change or ask for modifications.
If everything is OK, they will publish it.

Regarding the delays, it depends on how busy they are... I saw delay ranging from 2 weeks to 2 month...

**Comment by LucasArona** [comment]
Hello,
FYI: It's online now !

**Comment by leonhardhaas** [comment]
Hello again.

Thanks for the update and all the help :D

With best regards,
Leo

**Pull request merged**
